name: Review Service CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout review-service
        uses: actions/checkout@v4
        with:
          path: review-service

      - name: Checkout shared repo
        uses: actions/checkout@v4
        with:
          repository: ShopEcommerce/ecommerce_shop-shared
          path: shared

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: 'review-service/package-lock.json'

      - name: Build Shared Library
        run: |
          cd shared
          npm install
          npm run build
          npm pack

      - name: Install Dependencies
        run: |
          cd review-service
          npm install ../shared/teleshop-common-1.0.4.tgz
          npm install

      - name: Generate Prisma Client
        run: |
          cd review-service
          npx prisma generate

      - name: Run Linter
        run: |
          cd review-service
          npm run lint

      - name: Run Unit Tests
        run: |
          cd review-service
          npm run test:ci
